title: "Coloring Mojo"
description: "Free coloring pages and premium bundles for creative souls"
baseurl: ""
url: "https://coloringmojo.github.io"
markdown: kramdown
permalink: pretty

collections:
  posts:
    output: true
    permalink: /:title

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
